#devtools::install_github("trestletech/plumber")
library(plumber)
#r <- plumb("/home/hans/simple-peoplemover-jsonapi/my_file.R") 
r <- plumb("/home/ht/Desktop/git/api-realtime-bus/R/build_protobuf.R") 
r$run(port=8001)
